chore: fixup CI for docker-hosted php

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,22 +13,12 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v2
 
-    - name: Setup PHP 7.4
-      uses: shivammathur/setup-php@6972aed899fa2dd4016a7e314c46e6902bcafb7b
-      with:
-        php-version: '7.4'
-        extensions: curl, intl, mbstring, openssl
-        coverage: none
-      env:
-        fail-fast: true
-
     # Build the docker image and create link to vendor/ dependencies
     - name: Build the Docker image
       shell: bash
-      # --mount option requires BuildKit
       run: |
-        ./build.sh build start
         echo "TIER_TEST" > tier.txt
+        ./build.sh build start
       env:
         fail-fast: true
 
@@ -43,12 +33,23 @@ jobs:
     - name: Check broken links
       shell: bash
       run: |
-        ( set +e; set +o pipefail; npx broken-link-checker http://localhost:8055 --ordered --recursive --host-requests 50 -e --filter-level 3 | grep -E "BROKEN|Getting links from" | grep -B 1 "BROKEN"; exit ${PIPESTATUS[0]} )
+        set +e;
+        set +o pipefail;
+        npx broken-link-checker http://localhost:8055 --ordered --recursive --host-requests 50 -e --filter-level 3 | \
+          grep -E "BROKEN|Getting links from" | \
+          grep -B 1 "BROKEN"
+        exit ${PIPESTATUS[0]}
 
     - name: Check PHP errors
       shell: bash
       run: |
-        ( set +e; set +o pipefail; [ -f php_errors.log ] && echo 'PHP reported errors or warnings; see log below' && exit 1 || ( echo 'No PHP errors found' && exit 0 ) )
+        set +e
+        set +o pipefail
+        CONTAINER=`docker container ls -l -q`
+        docker container logs $CONTAINER | grep -q '[php7:error]' && \
+          ( echo 'No PHP errors found' && exit 0 ) || \
+          ( echo 'PHP reported errors or warnings; see log below' && exit 1 ) \
+        )
     #
     # If any of the tests fail, let's grab a bit more detail on the environment
     #
@@ -56,11 +57,8 @@ jobs:
       if: ${{ failure() }}
       shell: bash
       run: |
+        CONTAINER=`docker container ls -l -q`
         echo "--- tier.txt ---"
         cat tier.txt
         echo "--- Docker log ---"
-        docker container logs `docker container ls -l -q`
-        echo "--- PHP Errors ---"
-        [ -f php_errors.log ] && cat php_errors.log
-        echo "--- PHPInfo ---"
-        php -r 'phpinfo();'
+        docker container logs $CONTAINER
